# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [
    "asm",
#    "asm-tree" # merged in asm module
]

[workspace.package]
version = "0.0.1"
authors = ["zsqw123"]
edition = "2021"
description = "Java bytecode reader & writer in rust"
documentation = "https://example.com/bar" # todo need changes
