[package]
name = "java_asm"
version.workspace =  true
authors.workspace = true
edition.workspace = true

[dependencies]
java_asm_internal = { path = "../asm_internal" }
java_asm_macro = { path = "../asm_macro" }

[lib]
doctest = false
