[package]
name = "java_asm_server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
java_asm = { workspace = true }
bit-set = { workspace = true }
chrono = { workspace = true }

nucleo-matcher = { workspace = true }
rand = { workspace = true }
log = { workspace = true }

fontdb = { workspace = true }
rfd = { workspace = true }

enum_dispatch = { workspace = true }

parking_lot = { workspace = true }
futures = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
zip = { workspace = true, features = ["default"] }
tokio = { workspace = true, features = ["full"] }
open = { workspace = true }
rayon = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
zip = {
    workspace = true,
    features = ["deflate64", "deflate", "lzma", "time", "zstd"],
}
js-sys = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }
getrandom_v2 = { workspace = true, features = ["js"] }
tokio = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Window"] }
web-time = { workspace = true }
